controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    celconv_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    celconv_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


celconv_velocity_controller:
  ros__parameters:
    joints:
    # List of joints to control (leave empty for dynamic reconfiguration)
      
